[build]
  command = "npm install && npm run build"
  publish = "dist"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "20.0.0"
  NPM_VERSION = "10.0.0"
  YARN_VERSION = "1.22.0"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  framework = "vite"
  command = "npm run dev"
  port = 3000
  target = "dist"
  publish = "dist"
