[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--version"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  framework = "create-react-app"
  command = "npm start"
  port = 3000
  target = "."
  publish = "."

[functions]
  node_bundler = "esbuild"
